event void FSummitDecimatorSpikeBombAutoAimSignature();

class USummitDecimatorSpikeBombAutoAimComponent : UActorComponent
{
	FSummitDecimatorSpikeBombAutoAimSignature OnAutoAimAssistedHit;
	FSummitDecimatorSpikeBombAutoAimSignature OnManualAimHit;
};