event void FSummitDecimatorSpikeBombShockwaveResponseSignature();

class USummitDecimatorShockwaveSpikeBombResponseComponent : UActorComponent
{
	FSummitDecimatorSpikeBombShockwaveResponseSignature OnHitByShockwave;
};