event void IslandOverseerPeekBombLauncherComponentAttackEvent();

class UIslandOverseerPeekBombLauncherComponent : UBasicAIProjectileLauncherComponent
{
	IslandOverseerPeekBombLauncherComponentAttackEvent OnAttack;
}