
UCLASS(Abstract)
class UVO_Island_Stormdrain_ShieldOTronMultiple_SoundDef : UHazeVOSoundDef
{
	/* AUTO-GENERATED CODE - Anything from here to end should NOT be edited! */

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnLaunchRocketAttack(FIslandShieldotronRocketAttackPlayerEventData IslandShieldotronRocketAttackPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnLaunchMortarAttack(FIslandShieldotronMortarAttackPlayerEventData IslandShieldotronMortarAttackPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnStartTelegraphMortarAttack(FIslandShieldotronMortarTelegraphPlayerEventData IslandShieldotronMortarTelegraphPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnShieldotronStunned(FIslandShieldotronPlayerEventData IslandShieldotronPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnShieldotronDamage(FIslandShieldotronPlayerEventData IslandShieldotronPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnShieldotronDeath(FIslandShieldotronPlayerEventData IslandShieldotronPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandShieldotronPlayer_OnShieldotronStartDying(FIslandShieldotronPlayerEventData IslandShieldotronPlayerEventData){}

	UFUNCTION(BlueprintEvent)
	void IslandForceFieldPlayer_OnForceFieldSwitchedType(FIslandForceSwitchTypeParams IslandForceSwitchTypeParams){}

	UFUNCTION(BlueprintEvent)
	void IslandForceFieldPlayer_OnForceFieldDepleted(FIslandForceFieldDepletedPlayerEventParams IslandForceFieldDepletedPlayerEventParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenadeResponse_OnDetonate(FIslandRedBlueStickyGrenadeOnDetonateParams IslandRedBlueStickyGrenadeOnDetonateParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenadeResponse_OnAttached(FIslandRedBlueStickGrenadeOnAttachedData IslandRedBlueStickGrenadeOnAttachedData){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnAttached(FIslandRedBlueStickyGrenadeOnAttachedParams IslandRedBlueStickyGrenadeOnAttachedParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnResetGrenade(FIslandRedBlueStickyGrenadeBasicEffectParams IslandRedBlueStickyGrenadeBasicEffectParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnDespawnOnForceField(FIslandRedBlueStickyGrenadeOnDespawnOnForceFieldParams IslandRedBlueStickyGrenadeOnDespawnOnForceFieldParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnDetonate(FIslandRedBlueStickyGrenadeOnDetonateParams IslandRedBlueStickyGrenadeOnDetonateParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnThrowGrenade(FIslandRedBlueStickyGrenadeOnThrowParams IslandRedBlueStickyGrenadeOnThrowParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueForceField_OnForceFieldActivated(){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueForceField_OnForceFieldDestroyed(){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueForceField_OnNewHoleInForceField(FIslandRedBlueForceFieldOnGrenadeDetonateOnForceFieldParams IslandRedBlueForceFieldOnGrenadeDetonateOnForceFieldParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueForceField_OnBulletReflectOnForceField(FIslandRedBlueForceFieldOnBulletReflectOnForceFieldParams IslandRedBlueForceFieldOnBulletReflectOnForceFieldParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnAttachedAudio(FIslandRedBlueStickyGrenadeOnAttachedParams IslandRedBlueStickyGrenadeOnAttachedParams){}

	UFUNCTION(BlueprintEvent)
	void IslandRedBlueStickyGrenade_OnThrowGrenadeAudio(FIslandRedBlueStickyGrenadeOnThrowParams IslandRedBlueStickyGrenadeOnThrowParams){}

	/* END OF AUTO-GENERATED CODE */

}