asset SanctuaryEnvironmentLanternSwingSheet of UHazeCapabilitySheet
{
	Capabilities.Add(USanctuaryEnvironmentLanternSwingBirdCapability);
	Capabilities.Add(USanctuaryEnvironmentLanternSwingFishCapability);
}